services:
  services:
  - type: web
    name: telegram-bot
    env: python
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    buildCommand: pip install -U -r requirements.txt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
