services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: TELEGRAM_API_KEY
        value: your-telegram-api-key
      - key: DATABASE_URL
        value: your-database-url
    regions:
      - oregon
    # Uncomment below if you need to set a specific GitHub repository
    # git:
    #   repo: https://github.com/yourusername/your-repo
    #   branch: main
